// export { default as PaymentDisplay } from './PaymentDisplay';
// export { default as Payment } from './Payment';
export { default as PaymentInfo } from './PaymentInfo';
export { default as Cards } from './Cards';
export { default as Requirement } from './Requirement';
export { default as CardRequest } from './CardRequest';
export { default as SettingNav } from './SettingNav';
export { default as UserPersonalInfo } from './UserPersonalInfo';
export { default as MeansOfIdentity } from './MeansOfIdentity';
export { default as ProofOfAddress } from './ProofOfAddress';
export { default as SecuritySection } from './SecuritySection';
export { default as LoginUpdate } from './LoginUpdate';
export { default as BlockCard } from './BlockCard';
export { default as AboutMakeCards } from './AboutMakeCards';
export { default as ContactUs } from './ContactUs';
export { default as BlockCardModal } from './BlockCardModal';
export { default as FundCardAside } from './FundCardAside';
export { default as PaymentInfoAside } from './PaymentInfoAside';
export { default as TableComp } from './TableComp';
export { default as MobileTable } from './MobileTable';
export { default as TransactionTable } from './TransactionTable';
